name: test

on:
  push:
    branches:
      - master
      - 'develop-**'
      - 'bugfix/**'
      - 'feature/**'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    container: koalaman/shellcheck-alpine:v0.6.0
    steps:
    - uses: actions/checkout@v2
    - name: Run shellcheck
      run: shellcheck -s bash -f tty ./bin/xpanes ./*.sh

  shfmt:
    runs-on: ubuntu-latest
    container: mvdan/shfmt:v3.1.0-alpine
    steps:
    - uses: actions/checkout@v2
    - name: Run shfmt
      run: shfmt -i 2 -ci -sr -kp -d ./bin/xpanes ./*.sh

  test:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    container: bash:${{matrix.bash}}
    strategy:
      matrix:
        include:
###START_INSERT###
          - bash: "3.2"
            tmux: "1.8"
            cases: 3,6,7,9,10,12,22,26,39,42,45,48,69
          - bash: "3.2"
            tmux: "1.9"
            cases: 7,8,37,42,53,72,80
          - bash: "3.2"
            tmux: "1.9a"
            cases: 2,4,5,12,15,19,20,39,42,69
          - bash: "3.2"
            tmux: "2.0"
            cases: 1,5,22,27,34,41,48,57,65,72,78,83
          - bash: "3.2"
            tmux: "2.1"
            cases: 10,23,34,38,47,56,68,76,78
          - bash: "3.2"
            tmux: "2.2"
            cases: 4,5,6,17,22,24,31,32,33,45,47,64,84
          - bash: "3.2"
            tmux: "2.3"
            cases: 16,30,31,32,39,41,42,47,58,68,80,81,83
          - bash: "3.2"
            tmux: "2.4"
            cases: 3,22,25,27,30,46,71
          - bash: "3.2"
            tmux: "2.5"
            cases: 6,11,14,18,23,38,40,41,44,50,54,78,81,84
          - bash: "3.2"
            tmux: "2.6"
            cases: 18,19,28,31,45,63,66,78
          - bash: "3.2"
            tmux: "2.7"
            cases: 15,17,19,25,33,44,50,71,73,77,81,82,83
          - bash: "3.2"
            tmux: "2.8"
            cases: 5,14,17,21,24,28,40,51
          - bash: "3.2"
            tmux: "2.9"
            cases: 2,20,26,38,44,45,46,55,60,70,84
          - bash: "3.2"
            tmux: "2.9a"
            cases: 17,43,47,49,53,55,57,69,76,82
          - bash: "3.2"
            tmux: "3.0a"
            cases: 1,2,4,19,33,35,45,54,59,60,74,76,82
          - bash: "3.2"
            tmux: "3.1"
            cases: 12,13,16,37,46,53,55,61
          - bash: "3.2"
            tmux: "3.1b"
            cases: 26,29,36,50,52,59,63,70,71,79
          - bash: "3.2"
            tmux: "3.1c"
            cases: 8,41,48,62,67,75,77,82
          - bash: "4.0"
            tmux: "1.8"
            cases: 29,33,41,77,78,83
          - bash: "4.0"
            tmux: "1.9"
            cases: 9,12,18,19,38,39,43,44,57,62,77,79,83
          - bash: "4.0"
            tmux: "1.9a"
            cases: 17,22,29,40,61,65
          - bash: "4.0"
            tmux: "2.0"
            cases: 19,21,37,46,47,49,53,64,68,70
          - bash: "4.0"
            tmux: "2.1"
            cases: 11,13,16,25,32,49,55,64,65,69,82
          - bash: "4.0"
            tmux: "2.2"
            cases: 3,15,18,26,38,42,43,83
          - bash: "4.0"
            tmux: "2.3"
            cases: 10,11,14,18,22,28,71,76
          - bash: "4.0"
            tmux: "2.4"
            cases: 21,24,39,40,45,58,65,82
          - bash: "4.0"
            tmux: "2.5"
            cases: 27,35,55,65,69,82,83
          - bash: "4.0"
            tmux: "2.6"
            cases: 1,13,14,20,26,27,30,36,49,59,69,70,74
          - bash: "4.0"
            tmux: "2.7"
            cases: 45,54,58,59,62,65,66,72,76,80
          - bash: "4.0"
            tmux: "2.8"
            cases: 4,9,13,41,46,47,61,69
          - bash: "4.0"
            tmux: "2.9"
            cases: 6,9,13,16,22,35,49,62,65,80,83
          - bash: "4.0"
            tmux: "2.9a"
            cases: 5,7,11,21,27,31,32,37,48,54,56,75,78,79,83
          - bash: "4.0"
            tmux: "3.0a"
            cases: 12,23,34,36,44,49,72,79,84
          - bash: "4.0"
            tmux: "3.1"
            cases: 2,4,17,23,24,40,45,51,57,62,63,76,78,82
          - bash: "4.0"
            tmux: "3.1b"
            cases: 5,8,25,40,49,51,55,65,67,68
          - bash: "4.0"
            tmux: "3.1c"
            cases: 11,22,24,26,37,39,50,52,53,58,60,70,73,81
          - bash: "4.1"
            tmux: "1.8"
            cases: 19,21,23,27,28,34,38,43,47,57,62,71,81
          - bash: "4.1"
            tmux: "1.9"
            cases: 1,6,11,15,20,23,26,31,41,68
          - bash: "4.1"
            tmux: "1.9a"
            cases: 1,10,14,23,41,56,80,82
          - bash: "4.1"
            tmux: "2.0"
            cases: 4,8,9,10,16,31,32,54,62,71,79,81,82,84
          - bash: "4.1"
            tmux: "2.1"
            cases: 2,17,18,46,48,52,61,71,72,79
          - bash: "4.1"
            tmux: "2.2"
            cases: 9,12,27,28,69,78
          - bash: "4.1"
            tmux: "2.3"
            cases: 4,9,13,34,37,44,77
          - bash: "4.1"
            tmux: "2.4"
            cases: 13,14,17,23,31,35,42,43,56,69,76,80
          - bash: "4.1"
            tmux: "2.5"
            cases: 19,29,30,31,39,45,47,66
          - bash: "4.1"
            tmux: "2.6"
            cases: 5,12,16,22,39,41,46,52,53,83
          - bash: "4.1"
            tmux: "2.7"
            cases: 1,2,9,13,27,29,35,46,74,84
          - bash: "4.1"
            tmux: "2.8"
            cases: 6,15,30,37,38,67,76,79
          - bash: "4.1"
            tmux: "2.9"
            cases: 27,32,33,39,50,51,63,73,78
          - bash: "4.1"
            tmux: "2.9a"
            cases: 3,8,14,19,44,58,59,60
          - bash: "4.1"
            tmux: "3.0a"
            cases: 3,15,21,30,32,40,50,53,56,70,78
          - bash: "4.1"
            tmux: "3.1"
            cases: 10,11,20,22,25,49,52,65,75
          - bash: "4.1"
            tmux: "3.1b"
            cases: 2,10,15,21,24,28,41,46,77,83
          - bash: "4.1"
            tmux: "3.1c"
            cases: 7,16,18,25,36,38,40,47,51,55,59,64,66
          - bash: "4.2"
            tmux: "1.8"
            cases: 11,15,25,30,64,76
          - bash: "4.2"
            tmux: "1.9"
            cases: 16,17,22,28,40,49,51,65,70
          - bash: "4.2"
            tmux: "1.9a"
            cases: 7,11,21,27,37,47,54,55,62,83
          - bash: "4.2"
            tmux: "2.0"
            cases: 7,18,28,30,45,76
          - bash: "4.2"
            tmux: "2.1"
            cases: 5,6,26,35,36,39,40,50,53,57,58,83
          - bash: "4.2"
            tmux: "2.2"
            cases: 7,10,23,30,37,39,53,68,70,72
          - bash: "4.2"
            tmux: "2.3"
            cases: 2,6,26,29,38,40,45,69,82
          - bash: "4.2"
            tmux: "2.4"
            cases: 8,12,26,33,34,60,62
          - bash: "4.2"
            tmux: "2.5"
            cases: 25,34,36,43,56,59
          - bash: "4.2"
            tmux: "2.6"
            cases: 3,4,32,33,43,44,48,68,73,82,84
          - bash: "4.2"
            tmux: "2.7"
            cases: 3,4,5,8,10,20,23,26,30,31,32,38,41,68,70
          - bash: "4.2"
            tmux: "2.8"
            cases: 7,8,12,16,20,29,31,35,39,57,60,72,75
          - bash: "4.2"
            tmux: "2.9"
            cases: 1,3,10,21,24,47,57,61,66,68,77,79
          - bash: "4.2"
            tmux: "2.9a"
            cases: 12,13,16,23,40,63,64,68,81
          - bash: "4.2"
            tmux: "3.0a"
            cases: 14,17,20,27,29,42,46,52,57,64,71
          - bash: "4.2"
            tmux: "3.1"
            cases: 15,18,32,64,67,68,74
          - bash: "4.2"
            tmux: "3.1b"
            cases: 6,11,14,17,19,27,42,58,61,66,72,80,82
          - bash: "4.2"
            tmux: "3.1c"
            cases: 2,3,4,9,10,12,14,19,29,31,32,33,71,78,79,80
          - bash: "4.3"
            tmux: "1.8"
            cases: 8,18,20,40,46,55,61,79
          - bash: "4.3"
            tmux: "1.9"
            cases: 3,21,24,27,32,34,35,36,64,69,71,78,82,84
          - bash: "4.3"
            tmux: "1.9a"
            cases: 8,25,28,49,52,57,70,78,81,84
          - bash: "4.3"
            tmux: "2.0"
            cases: 6,13,14,15,23,29,35,36,50,69,77
          - bash: "4.3"
            tmux: "2.1"
            cases: 1,4,19,31,37,42,45,54,84
          - bash: "4.3"
            tmux: "2.2"
            cases: 20,25,41,49,52,54,62,65,81
          - bash: "4.3"
            tmux: "2.3"
            cases: 3,7,17,23,55,72
          - bash: "4.3"
            tmux: "2.4"
            cases: 1,4,10,28,36,44,48,51,52,53,55,57,64,70,72,81
          - bash: "4.3"
            tmux: "2.5"
            cases: 4,5,7,8,10,12,13,15,16,28,53,67,72,76,79,80
          - bash: "4.3"
            tmux: "2.6"
            cases: 15,17,34,42,54,56,58,60,75
          - bash: "4.3"
            tmux: "2.7"
            cases: 7,11,43,47,48,52,63,78
          - bash: "4.3"
            tmux: "2.8"
            cases: 2,19,22,25,26,42,44,45,62,73,74,78,83
          - bash: "4.3"
            tmux: "2.9"
            cases: 11,17,18,34,36,52,59,67
          - bash: "4.3"
            tmux: "2.9a"
            cases: 6,15,20,22,29,30,50,51,62,66,70,74,80
          - bash: "4.3"
            tmux: "3.0a"
            cases: 9,10,26,28,68,69
          - bash: "4.3"
            tmux: "3.1"
            cases: 14,26,27,31,33,38,50,56,71,72,81,84
          - bash: "4.3"
            tmux: "3.1b"
            cases: 34,39,44
          - bash: "4.3"
            tmux: "3.1c"
            cases: 5,13,23,27,43,44,45,61,76
          - bash: "4.4"
            tmux: "1.8"
            cases: 2,4,16,36,65
          - bash: "4.4"
            tmux: "1.9"
            cases: 5,10,25,29,30,45,46,47,54,55,58
          - bash: "4.4"
            tmux: "1.9a"
            cases: 6,26,30,34,35,36,38,50,53,72
          - bash: "4.4"
            tmux: "2.0"
            cases: 24,26,39,40,42,80
          - bash: "4.4"
            tmux: "2.1"
            cases: 7,9,12,15,20,22,28,29,30,44,62,80,81
          - bash: "4.4"
            tmux: "2.2"
            cases: 13,14,16,21,29,44,48,57
          - bash: "4.4"
            tmux: "2.3"
            cases: 12,19,25,65,66,70
          - bash: "4.4"
            tmux: "2.4"
            cases: 5,7,11,15,18,20,37,54,59,67,78,83
          - bash: "4.4"
            tmux: "2.5"
            cases: 1,2,3,17,20,24,32,33,58,60,68,71,77
          - bash: "4.4"
            tmux: "2.6"
            cases: 2,23,24,37,51,64,67,79,81
          - bash: "4.4"
            tmux: "2.7"
            cases: 6,12,18,21,42,49,53,56,57,79
          - bash: "4.4"
            tmux: "2.8"
            cases: 10,11,27,32,43,52,55,71,81,82
          - bash: "4.4"
            tmux: "2.9"
            cases: 4,14,31,41,48,72,75,76
          - bash: "4.4"
            tmux: "2.9a"
            cases: 18,46,52,65,84
          - bash: "4.4"
            tmux: "3.0a"
            cases: 6,8,13,22,24,38,43,47,58,61,63,67
          - bash: "4.4"
            tmux: "3.1"
            cases: 1,3,7,28,34,39,48,69,73,77
          - bash: "4.4"
            tmux: "3.1b"
            cases: 3,18,33,35,37,60,62,64,74,75,84
          - bash: "4.4"
            tmux: "3.1c"
            cases: 1,20,30,34,46,83
          - bash: "5.0"
            tmux: "1.8"
            cases: 17,24,35,37,44,68,70,80
          - bash: "5.0"
            tmux: "1.9"
            cases: 14,33,48,56,61
          - bash: "5.0"
            tmux: "1.9a"
            cases: 3,13,18,24,45,51,58,64,76,77,79
          - bash: "5.0"
            tmux: "2.0"
            cases: 2,11,20,25,33,38,44,52,56,58,61
          - bash: "5.0"
            tmux: "2.1"
            cases: 3,8,14,24,27,33,41,43
          - bash: "5.0"
            tmux: "2.2"
            cases: 36,46,50,56,58,76,77,79,80
          - bash: "5.0"
            tmux: "2.3"
            cases: 8,21,33,36,43,48,57,60,78,79
          - bash: "5.0"
            tmux: "2.4"
            cases: 2,6,41,49,50,84
          - bash: "5.0"
            tmux: "2.5"
            cases: 21,22,42,46,48,49,51,52,57,62,64,70
          - bash: "5.0"
            tmux: "2.6"
            cases: 6,9,21,29,35,47,55,62,71,72,77
          - bash: "5.0"
            tmux: "2.7"
            cases: 16,22,39,40,67
          - bash: "5.0"
            tmux: "2.8"
            cases: 34,36,48,49,50,53,54,56,64,66,77
          - bash: "5.0"
            tmux: "2.9"
            cases: 7,12,15,29,30,40,58,69,71,74,81,82
          - bash: "5.0"
            tmux: "2.9a"
            cases: 1,4,10,26,28,33,34,38,41,42,61,73
          - bash: "5.0"
            tmux: "3.0a"
            cases: 5,11,25,31,39,55,66,73,75,77,83
          - bash: "5.0"
            tmux: "3.1"
            cases: 8,9,19,35,41,42,44,47,54,58,59,60,70,79,80
          - bash: "5.0"
            tmux: "3.1b"
            cases: 1,4,12,13,16,20,23,30,32,53,57,81
          - bash: "5.0"
            tmux: "3.1c"
            cases: 6,28,42,56,57,63,65,68,69
          - bash: "5.1"
            tmux: "1.8"
            cases: 13,14,58,72,82
          - bash: "5.1"
            tmux: "1.9"
            cases: 2,4,13,50,52,76,81
          - bash: "5.1"
            tmux: "1.9a"
            cases: 9,16,31,32,33,43,44,46,48,68,71
          - bash: "5.1"
            tmux: "2.0"
            cases: 3,12,17,43,51,55
          - bash: "5.1"
            tmux: "2.1"
            cases: 21,51,70,77
          - bash: "5.1"
            tmux: "2.2"
            cases: 1,2,8,11,19,34,35,40,51,55,61,71,82
          - bash: "5.1"
            tmux: "2.3"
            cases: 15,20,24,27,35,46,59,64,67
          - bash: "5.1"
            tmux: "2.4"
            cases: 9,16,19,29,32,38,47,66,68,77,79
          - bash: "5.1"
            tmux: "2.5"
            cases: 9,26,37
          - bash: "5.1"
            tmux: "2.6"
            cases: 7,8,10,11,25,38,40,50,57,65,76,80
          - bash: "5.1"
            tmux: "2.7"
            cases: 14,24,28,34,36,37,51,55,60,64,69,75
          - bash: "5.1"
            tmux: "2.8"
            cases: 1,3,18,23,33,58,59,63,65,68,70,80,84
          - bash: "5.1"
            tmux: "2.9"
            cases: 5,8,19,23,25,28,37,42,43,53,54,56,64
          - bash: "5.1"
            tmux: "2.9a"
            cases: 2,9,24,25,35,36,39,45,67,71,72,77
          - bash: "5.1"
            tmux: "3.0a"
            cases: 7,16,18,37,41,48,51,62,65,80,81
          - bash: "5.1"
            tmux: "3.1"
            cases: 5,6,21,29,30,36,43,66,83
          - bash: "5.1"
            tmux: "3.1b"
            cases: 7,9,22,31,38,43,45,47,48,54,56,69,73,76,78
          - bash: "5.1"
            tmux: "3.1c"
            cases: 15,17,21,35,49,54,72,74,84
###END_INSERT###

    steps:
    - uses: actions/checkout@v2
    - name: Install dependency
      run: |
        apk add make curl gcc musl-dev libevent-dev ncurses-dev perl git util-linux bsd-compat-headers
        git clone -b v2.1.8 https://github.com/kward/shunit2.git test/shunit2

    - name: Install tmux
      run: |
        curl -L "https://github.com/tmux/tmux/releases/download/${{matrix.tmux}}/tmux-${{matrix.tmux}}.tar.gz" | tar zxv
        cd tmux-${{matrix.tmux}}
        ./configure
        make
        make install
        printf "set-window-option -g automatic-rename off\nset-option -g allow-rename off\n" >> "$HOME/.tmux.conf"

    - name: Unit test
      run: |
        script -e -c /bin/bash -c 'TERM=xterm bash ./test/unit.sh'

    - name: Scenario test
      run: |
        bash ./test/test_generator.sh ${{matrix.cases}} > ./test/cases_pairwise.sh
        script -e -c /bin/bash -c 'stty rows 40 cols 80;TERM=xterm bash ./test/cases_pairwise.sh'
