name: test

on:
  push:
    branches:
      - master
      - 'develop-**'
      - 'bugfix/**'
      - 'feature/**'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    container: koalaman/shellcheck-alpine:v0.6.0
    steps:
    - uses: actions/checkout@v2
    - name: Run shellcheck
      run: shellcheck -s bash -f tty ./bin/xpanes ./*.sh

  shfmt:
    runs-on: ubuntu-latest
    container: mvdan/shfmt:v3.1.0-alpine
    steps:
    - uses: actions/checkout@v2
    - name: Run shfmt
      run: shfmt -i 2 -ci -sr -kp -d ./bin/xpanes ./*.sh

  test:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    container: bash:${{matrix.bash}}
    strategy:
      matrix:
        include:
###START_INSERT###
          - bash: "3.2"
            tmux: "1.8"
            cases: 6,21,29,34,37,44,58,61,62,64,72,83
          - bash: "3.2"
            tmux: "1.9"
            cases: 3,13,23,27,30,35,58,69,78
          - bash: "3.2"
            tmux: "1.9a"
            cases: 2,5,9,10,13,24,34,35,41,46,47,53,72
          - bash: "3.2"
            tmux: "2.0"
            cases: 11,17,23,25,26,32,33,48,50,52,62,80
          - bash: "3.2"
            tmux: "2.1"
            cases: 1,2,3,13,19,28,32,33,41,44,47,49,54,68,81,84
          - bash: "3.2"
            tmux: "2.2"
            cases: 2,3,5,11,16,20,22,27,35,39,40,41,46,47,55,57,61,78
          - bash: "3.2"
            tmux: "2.3"
            cases: 6,28,42,44,55,70,72,76,78
          - bash: "3.2"
            tmux: "2.4"
            cases: 10,60,83
          - bash: "3.2"
            tmux: "2.5"
            cases: 11,26,29,38,48,55,69,71,81
          - bash: "3.2"
            tmux: "2.6"
            cases: 3,10,32,36,52,62,76,79
          - bash: "3.2"
            tmux: "2.7"
            cases: 8,10,15,18,22,25,39,44,49,57,59,68,78,79,82
          - bash: "3.2"
            tmux: "2.8"
            cases: 1,5,7,32,37,42,45,48,50,54,68,80,81
          - bash: "3.2"
            tmux: "2.9"
            cases: 9,15,23,24,26,28,30,31,37,45,49,53,56,68,69,70,71,72,73,74,79
          - bash: "3.2"
            tmux: "2.9a"
            cases: 1,7,10,16,30,43,51,53,66,67,78,79
          - bash: "3.2"
            tmux: "3.0a"
            cases: 3,39,48,52,61,68,75,77
          - bash: "3.2"
            tmux: "3.1"
            cases: 18,38,43,62,64,65,74,79
          - bash: "3.2"
            tmux: "3.1b"
            cases: 9,12,14,22,23,29,35,48,63,71,73,76,81
          - bash: "3.2"
            tmux: "3.1c"
            cases: 4,6,12,27,31,33,41,45,52,61,65
          - bash: "4.0"
            tmux: "1.8"
            cases: 4,7,10,22,24,36,41,45,77,81
          - bash: "4.0"
            tmux: "1.9"
            cases: 2,15,18,24,26,29,34,49,61,62,68,82
          - bash: "4.0"
            tmux: "1.9a"
            cases: 1,8,12,16,18,44,52,55,58,70,71,76
          - bash: "4.0"
            tmux: "2.0"
            cases: 1,9,13,16,19,20,21,29,31,37,56,82
          - bash: "4.0"
            tmux: "2.1"
            cases: 9,25,31,35,48,50,55,69,72,76,79
          - bash: "4.0"
            tmux: "2.2"
            cases: 7,15,24,26,28,31,33,34,37,44,52
          - bash: "4.0"
            tmux: "2.3"
            cases: 3,4,8,13,21,31,32,34,57,64
          - bash: "4.0"
            tmux: "2.4"
            cases: 4,6,9,17,19,22,27,29,35,43,50,62,77,78,81,82,84
          - bash: "4.0"
            tmux: "2.5"
            cases: 18,20,21,28,32,39,42,62,67,79
          - bash: "4.0"
            tmux: "2.6"
            cases: 23,24,25,26,28,30,40,46,48,49,65,74,75,78
          - bash: "4.0"
            tmux: "2.7"
            cases: 6,17,27,31,50,52,55,56,84
          - bash: "4.0"
            tmux: "2.8"
            cases: 6,11,12,15,16,21,24,46,49,73,79
          - bash: "4.0"
            tmux: "2.9"
            cases: 3,11,16,17,18,38,39,46,47,64,83
          - bash: "4.0"
            tmux: "2.9a"
            cases: 6,14,25,38,40,46,58,68,77,83
          - bash: "4.0"
            tmux: "3.0a"
            cases: 4,12,32,33,36,38,41,47,50,57,63,66,72,79
          - bash: "4.0"
            tmux: "3.1"
            cases: 7,45,47,53,56,59,70,71,78,83,84
          - bash: "4.0"
            tmux: "3.1b"
            cases: 6,13,25,28,43,56,69,72,79,80,82
          - bash: "4.0"
            tmux: "3.1c"
            cases: 2,5,8,16,25,29,30,40,51,53,54,60,64,68,78,80,82
          - bash: "4.1"
            tmux: "1.8"
            cases: 11,20,25,28,46,68,69,70,71,82
          - bash: "4.1"
            tmux: "1.9"
            cases: 6,7,9,11,14,17,22,33,38,43,51,65
          - bash: "4.1"
            tmux: "1.9a"
            cases: 4,20,21,26,31,50,69,77,79,81,84
          - bash: "4.1"
            tmux: "2.0"
            cases: 7,15,28,30,36,46,49,53,54,58,64,70,72,79
          - bash: "4.1"
            tmux: "2.1"
            cases: 16,17,18,23,56,57,62
          - bash: "4.1"
            tmux: "2.2"
            cases: 8,9,14,17,21,29,30,38,58,71
          - bash: "4.1"
            tmux: "2.3"
            cases: 26,30,36,39,40,47,58,59,65,68,77,81
          - bash: "4.1"
            tmux: "2.4"
            cases: 8,11,12,18,23,24,26,32,33,52,54,56,66,76
          - bash: "4.1"
            tmux: "2.5"
            cases: 1,2,15,22,27,30,31,40,41,49,51,52,60,65,76,77,83
          - bash: "4.1"
            tmux: "2.6"
            cases: 9,13,17,18,33,45,53,54,58,64,73,84
          - bash: "4.1"
            tmux: "2.7"
            cases: 3,4,7,9,11,12,24,29,32,36,41,46,48,53,73,74,80
          - bash: "4.1"
            tmux: "2.8"
            cases: 3,33,39,44,51,56,58,75
          - bash: "4.1"
            tmux: "2.9"
            cases: 6,8,10,41,62,65,66
          - bash: "4.1"
            tmux: "2.9a"
            cases: 8,15,19,28,39,54,55,56,70,82
          - bash: "4.1"
            tmux: "3.0a"
            cases: 8,17,20,25,30,49,55,65,76
          - bash: "4.1"
            tmux: "3.1"
            cases: 4,6,17,36,48,52,61,63,67,82
          - bash: "4.1"
            tmux: "3.1b"
            cases: 2,4,5,10,15,31,34,36,37,42,44,49,50,51,57,62,66,70,75,78
          - bash: "4.1"
            tmux: "3.1c"
            cases: 13,18,22,35,42,44,47,57,63,67,70,71,72
          - bash: "4.2"
            tmux: "1.8"
            cases: 8,12,27,35,39,42,48,76,78
          - bash: "4.2"
            tmux: "1.9"
            cases: 5,21,28,42,44,45,46,53,55,71,72,79,80
          - bash: "4.2"
            tmux: "1.9a"
            cases: 3,6,7,14,15,27,28,36,39,40,42,45,51,65
          - bash: "4.2"
            tmux: "2.0"
            cases: 2,4,5,8,34,40,44,47,55,65,68,69
          - bash: "4.2"
            tmux: "2.1"
            cases: 4,6,8,10,15,24,26,29,39,61,70,71,77,80
          - bash: "4.2"
            tmux: "2.2"
            cases: 6,12,18,23,53,68,76,81,83
          - bash: "4.2"
            tmux: "2.3"
            cases: 10,12,15,20,33,35,37,38,46
          - bash: "4.2"
            tmux: "2.4"
            cases: 3,7,14,15,25,30,37,41,42,64,69
          - bash: "4.2"
            tmux: "2.5"
            cases: 9,12,14,16,24,35,56,68,80,82
          - bash: "4.2"
            tmux: "2.6"
            cases: 2,11,14,16,22,31,47,51,68,70,72
          - bash: "4.2"
            tmux: "2.7"
            cases: 19,26,35,38,43,51,54,58,60,64,67,72,75,76
          - bash: "4.2"
            tmux: "2.8"
            cases: 8,17,18,19,26,36,41,60,61,62,65,78,82,83
          - bash: "4.2"
            tmux: "2.9"
            cases: 1,2,40,43,55,59,63,77,78,81
          - bash: "4.2"
            tmux: "2.9a"
            cases: 3,4,9,11,13,26,29,31,36,49,50,52,57,59,60,76,84
          - bash: "4.2"
            tmux: "3.0a"
            cases: 1,2,19,23,27,34,37,42,44,60,62,70,74,78,84
          - bash: "4.2"
            tmux: "3.1"
            cases: 1,2,5,14,24,25,29,32,34,35,42,46,50,66,72,73,76,77
          - bash: "4.2"
            tmux: "3.1b"
            cases: 1,7,17,21,30,52,58,77
          - bash: "4.2"
            tmux: "3.1c"
            cases: 1,14,21,32,37,48,69,81,84
          - bash: "4.3"
            tmux: "1.8"
            cases: 2,14,15,17,18,33,40,65
          - bash: "4.3"
            tmux: "1.9"
            cases: 8,12,32,37,47,48,52,54,70,77
          - bash: "4.3"
            tmux: "1.9a"
            cases: 19,49,54,61,62,64,78,82
          - bash: "4.3"
            tmux: "2.0"
            cases: 12,14,38,39,51,57,81,83
          - bash: "4.3"
            tmux: "2.1"
            cases: 11,14,27,30,36,40,43,45,58,64
          - bash: "4.3"
            tmux: "2.2"
            cases: 4,62,72,77,80
          - bash: "4.3"
            tmux: "2.3"
            cases: 14,22,24,67,83
          - bash: "4.3"
            tmux: "2.4"
            cases: 1,28,40,48,53,58,65,67,71,72,80
          - bash: "4.3"
            tmux: "2.5"
            cases: 5,8,13,25,34,36,46,54,58,64,66
          - bash: "4.3"
            tmux: "2.6"
            cases: 5,7,15,21,35,37,39,41,42,43,44,50,59,60,66,69,77,80
          - bash: "4.3"
            tmux: "2.7"
            cases: 5,16,28,30,40
          - bash: "4.3"
            tmux: "2.8"
            cases: 10,13,23,28,43,47,53,63,71
          - bash: "4.3"
            tmux: "2.9"
            cases: 4,5,22,29,33,34,35,44,51,54,67,75,82,84
          - bash: "4.3"
            tmux: "2.9a"
            cases: 18,20,21,23,24,34,37,63,65,73,80
          - bash: "4.3"
            tmux: "3.0a"
            cases: 6,7,11,14,16,18,22,26,29,54,59,67,69,81,82
          - bash: "4.3"
            tmux: "3.1"
            cases: 3,8,9,10,12,16,27,30,31,49,51,60,68,69,80
          - bash: "4.3"
            tmux: "3.1b"
            cases: 3,11,26,27,33,39,45,55,61,64,74
          - bash: "4.3"
            tmux: "3.1c"
            cases: 3,7,17,19,24,46,50,55,56,59,76,79
          - bash: "4.4"
            tmux: "1.8"
            cases: 9,13,16,23,26,38,43,47,79
          - bash: "4.4"
            tmux: "1.9"
            cases: 1,10,20,25,39,40,41,56,57,76
          - bash: "4.4"
            tmux: "1.9a"
            cases: 11,22,23,25,29,30,32,33,37,38,48,80
          - bash: "4.4"
            tmux: "2.0"
            cases: 6,10,24,35,43,71,77,84
          - bash: "4.4"
            tmux: "2.1"
            cases: 12,22,34,37,38,42,51,52,53,65,78,82
          - bash: "4.4"
            tmux: "2.2"
            cases: 1,10,19,25,42,45,48,65,69,70,82,84
          - bash: "4.4"
            tmux: "2.3"
            cases: 2,7,9,16,17,18,23,43,45,48,60,79,82
          - bash: "4.4"
            tmux: "2.4"
            cases: 5,16,20,36,45,47,49,59,68,79
          - bash: "4.4"
            tmux: "2.5"
            cases: 3,4,7,23,33,37,44,57,70,78,84
          - bash: "4.4"
            tmux: "2.6"
            cases: 4,6,12,19,27,29,55,57,63,67,81
          - bash: "4.4"
            tmux: "2.7"
            cases: 1,21,47,62,66,70,71,81,83
          - bash: "4.4"
            tmux: "2.8"
            cases: 2,14,20,25,27,30,35,40,55,57,66,69,72,77
          - bash: "4.4"
            tmux: "2.9"
            cases: 12,13,19,20,21,25,36,42,50,52,57,60,61,76
          - bash: "4.4"
            tmux: "2.9a"
            cases: 2,5,17,27,33,35,41,42,61,64,74,75
          - bash: "4.4"
            tmux: "3.0a"
            cases: 10,15,21,24,31,40,46,56,58,71,80
          - bash: "4.4"
            tmux: "3.1"
            cases: 11,20,22,28,39,40,41,44,54,55,57,81
          - bash: "4.4"
            tmux: "3.1b"
            cases: 8,18,19,20,32,41,46,53,59,65,67
          - bash: "4.4"
            tmux: "3.1c"
            cases: 10,15,23,36,38,43,58,62,73,74,75,83
          - bash: "5.0"
            tmux: "1.8"
            cases: 3,19,30,55,57,80
          - bash: "5.0"
            tmux: "1.9"
            cases: 4,16,19,31,36,50,64,81,83,84
          - bash: "5.0"
            tmux: "1.9a"
            cases: 17,43,56,57,68,83
          - bash: "5.0"
            tmux: "2.0"
            cases: 3,18,22,27,41,42,45,61,76,78
          - bash: "5.0"
            tmux: "2.1"
            cases: 5,7,20,21,46,83
          - bash: "5.0"
            tmux: "2.2"
            cases: 13,32,36,43,49,50,51,54,56,64,79
          - bash: "5.0"
            tmux: "2.3"
            cases: 11,19,25,27,29,41,66,69,71,80
          - bash: "5.0"
            tmux: "2.4"
            cases: 2,13,21,31,34,38,39,44,46,51,55,57,70
          - bash: "5.0"
            tmux: "2.5"
            cases: 6,10,17,19,43,45,47,50,53,59,72
          - bash: "5.0"
            tmux: "2.6"
            cases: 1,8,20,34,38,56,71,82,83
          - bash: "5.0"
            tmux: "2.7"
            cases: 2,13,14,20,23,33,34,37,42,45,63,65,69,77
          - bash: "5.0"
            tmux: "2.8"
            cases: 4,9,22,29,31,34,38,52,59,64,67,70,74,76,84
          - bash: "5.0"
            tmux: "2.9"
            cases: 7,14,27,32,48,58,80
          - bash: "5.0"
            tmux: "2.9a"
            cases: 12,22,32,44,45,47,48,62,69,71,72,81
          - bash: "5.0"
            tmux: "3.0a"
            cases: 5,9,13,28,35,43,45,51,53,64,73,83
          - bash: "5.0"
            tmux: "3.1"
            cases: 13,15,19,21,23,26,33,37,58,75
          - bash: "5.0"
            tmux: "3.1b"
            cases: 16,24,38,40,47,54,60,68,83,84
          - bash: "5.0"
            tmux: "3.1c"
            cases: 9,11,20,26,28,34,39,49,66,77
###END_INSERT###

    steps:
    - uses: actions/checkout@v2
    - name: Install dependency
      run: |
        apk add make curl gcc musl-dev libevent-dev ncurses-dev perl git util-linux bsd-compat-headers
        git clone -b v2.1.8 https://github.com/kward/shunit2.git test/shunit2

    - name: Install tmux
      run: |
        curl -L "https://github.com/tmux/tmux/releases/download/${{matrix.tmux}}/tmux-${{matrix.tmux}}.tar.gz" | tar zxv
        cd tmux-${{matrix.tmux}}
        ./configure
        make
        make install
        printf "set-window-option -g automatic-rename off\nset-option -g allow-rename off\n" >> "$HOME/.tmux.conf"

    - name: Unit test
      run: |
        script -e -c /bin/bash -c 'TERM=xterm bash ./test/unit.sh'

    - name: Scenario test
      run: |
        bash ./test/test_generator.sh ${{matrix.cases}} > ./test/cases_pairwise.sh
        script -e -c /bin/bash -c 'stty rows 40 cols 80;TERM=xterm bash ./test/cases_pairwise.sh'
