name: test

on:
  push:
    branches:
      - master
      - 'develop-**'
      - 'bugfix/**'
      - 'feature/**'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    container: koalaman/shellcheck-alpine:v0.6.0
    steps:
    - uses: actions/checkout@v2
    - name: Run shellcheck
      run: shellcheck -s bash -f tty ./bin/xpanes ./*.sh

  shfmt:
    runs-on: ubuntu-latest
    container: mvdan/shfmt:v3.1.0-alpine
    steps:
    - uses: actions/checkout@v2
    - name: Run shfmt
      run: shfmt -i 2 -ci -sr -kp -d ./bin/xpanes ./*.sh

  test:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    container: bash:${{matrix.bash}}
    strategy:
      matrix:
        include:
###START_INSERT###
          - bash: "3.2"
            tmux: "1.8"
            cases: 12,29,30,64,72
          - bash: "3.2"
            tmux: "1.9"
            cases: 29,31,52,56,65,68
          - bash: "3.2"
            tmux: "1.9a"
            cases: 3,5,22,27,34,45,55,77
          - bash: "3.2"
            tmux: "2.0"
            cases: 9,28,31,38,50,55,78
          - bash: "3.2"
            tmux: "2.1"
            cases: 7,16,17,20,23,32,45,48,64
          - bash: "3.2"
            tmux: "2.2"
            cases: 3,4,17,26,41,43,51,54,57,65,70
          - bash: "3.2"
            tmux: "2.3"
            cases: 3,4,7,11,17,18,40,67
          - bash: "3.2"
            tmux: "2.4"
            cases: 11,22,34,40,57,62,76,84
          - bash: "3.2"
            tmux: "2.5"
            cases: 9,10,19,20,25,34,36,42,46,62,69,72,80,82
          - bash: "3.2"
            tmux: "2.6"
            cases: 2,6,33,35,39,52,75
          - bash: "3.2"
            tmux: "2.7"
            cases: 16,19,37,46,49,69,78,84
          - bash: "3.2"
            tmux: "2.8"
            cases: 10,24,35,47,49,63,73,74,80
          - bash: "3.2"
            tmux: "2.9"
            cases: 7,8,13,33,35,64,69,71,76,79,83
          - bash: "3.2"
            tmux: "2.9a"
            cases: 21,23,26,32,54,56,64,75,81,83,84
          - bash: "3.2"
            tmux: "3.0a"
            cases: 3,9,10,16,25,30,32,44,46,47,53,59,70,72,79
          - bash: "3.2"
            tmux: "3.1"
            cases: 4,6,21,23,24,35,45,49,61,64,66,80
          - bash: "3.2"
            tmux: "3.1b"
            cases: 1,15,25,26,31,41,58,60,63
          - bash: "3.2"
            tmux: "3.1c"
            cases: 11,13,28,40,41,43,47,52,63
          - bash: "3.2"
            tmux: "3.2"
            cases: 6,7,11,19,22,36,43,56,82
          - bash: "3.2"
            tmux: "3.3a"
            cases: 14,25,26,38,42,60,73,83
          - bash: "4.0"
            tmux: "1.8"
            cases: 16,34,39,41,79,82
          - bash: "4.0"
            tmux: "1.9"
            cases: 6,26,49,64
          - bash: "4.0"
            tmux: "1.9a"
            cases: 23,35,38,43,46,56,57
          - bash: "4.0"
            tmux: "2.0"
            cases: 11,13,17,34,36,39,42,65,68,76
          - bash: "4.0"
            tmux: "2.1"
            cases: 2,5,18,30,33,36,44,78
          - bash: "4.0"
            tmux: "2.2"
            cases: 14,19,30,72,77
          - bash: "4.0"
            tmux: "2.3"
            cases: 6,10,12,21,25,29,47,71,81
          - bash: "4.0"
            tmux: "2.4"
            cases: 2,12,16,23,37,48,79
          - bash: "4.0"
            tmux: "2.5"
            cases: 7,8,15,28,31,47,48,52,54,55,60,71,77
          - bash: "4.0"
            tmux: "2.6"
            cases: 1,8,9,19,23,27,28,31,36,45,76,80
          - bash: "4.0"
            tmux: "2.7"
            cases: 8,14,31,39,48,50,58,62,63,65
          - bash: "4.0"
            tmux: "2.8"
            cases: 13,32,38,40,46,54,83
          - bash: "4.0"
            tmux: "2.9"
            cases: 1,11,14,22,44,54,70
          - bash: "4.0"
            tmux: "2.9a"
            cases: 5,8,12,41,47,59,60,61,65,73,74
          - bash: "4.0"
            tmux: "3.0a"
            cases: 24,38,45,62,76,81,84
          - bash: "4.0"
            tmux: "3.1"
            cases: 3,20,42,50,51,52,67,69
          - bash: "4.0"
            tmux: "3.1b"
            cases: 2,18,21,27,32,66,75,79
          - bash: "4.0"
            tmux: "3.1c"
            cases: 19,24,37,57,59,62,66,69
          - bash: "4.0"
            tmux: "3.2"
            cases: 4,5,27,37,61,80
          - bash: "4.0"
            tmux: "3.3a"
            cases: 20,27,37,41,53,58,76,80
          - bash: "4.1"
            tmux: "1.8"
            cases: 3,83
          - bash: "4.1"
            tmux: "1.9"
            cases: 1,21,22,35,53,55,62
          - bash: "4.1"
            tmux: "1.9a"
            cases: 9,13,17,21,31,47,58,80,83
          - bash: "4.1"
            tmux: "2.0"
            cases: 6,7,23,45,54,71,82
          - bash: "4.1"
            tmux: "2.1"
            cases: 8,27,37,39,41,72,83,84
          - bash: "4.1"
            tmux: "2.2"
            cases: 10,12,52,71
          - bash: "4.1"
            tmux: "2.3"
            cases: 20,26,35,44,55,57,82
          - bash: "4.1"
            tmux: "2.4"
            cases: 3,25,33,36,43,49,51,56,68,71,81
          - bash: "4.1"
            tmux: "2.5"
            cases: 4,5,30,44,59,67,79
          - bash: "4.1"
            tmux: "2.6"
            cases: 4,10,16,48,50,59,60,65,78
          - bash: "4.1"
            tmux: "2.7"
            cases: 10,11,17,22,23,32,34,40,51,60,67
          - bash: "4.1"
            tmux: "2.8"
            cases: 1,3,9,27,29,36,37,45,50,51,53,56,65,72
          - bash: "4.1"
            tmux: "2.9"
            cases: 2,5,6,20,23,24,25,28,31,45,50,72
          - bash: "4.1"
            tmux: "2.9a"
            cases: 6,7,16,17,19,35,38,46,55,66,67,72
          - bash: "4.1"
            tmux: "3.0a"
            cases: 4,7,15,20,23,26,39,42,50,64,67,68
          - bash: "4.1"
            tmux: "3.1"
            cases: 9,13,15,16,18,27,43,54,56,62,73,75,76,84
          - bash: "4.1"
            tmux: "3.1b"
            cases: 12,23,30,37,55,74,76,80
          - bash: "4.1"
            tmux: "3.1c"
            cases: 6,8,14,32,33,42,45,61
          - bash: "4.1"
            tmux: "3.2"
            cases: 2,15,17,41,70,78,79,84
          - bash: "4.1"
            tmux: "3.3a"
            cases: 2,3,5,16,21,49,63,69,74,77
          - bash: "4.2"
            tmux: "1.8"
            cases: 9,14,21,23,48,70,71,78,80
          - bash: "4.2"
            tmux: "1.9"
            cases: 8,14,16,23,24,27,37,48,57,79
          - bash: "4.2"
            tmux: "1.9a"
            cases: 7,10,14,18,32,44,78
          - bash: "4.2"
            tmux: "2.0"
            cases: 4,20,27,35,48,52,57,62,79,83
          - bash: "4.2"
            tmux: "2.1"
            cases: 4,6,12,26,47,49,58,71
          - bash: "4.2"
            tmux: "2.2"
            cases: 2,5,15,20,22,33,34,36,44,47
          - bash: "4.2"
            tmux: "2.3"
            cases: 39,58,59,64,68,72
          - bash: "4.2"
            tmux: "2.4"
            cases: 1,9,15,38,39,41,42,52,54,58,70,82,83
          - bash: "4.2"
            tmux: "2.5"
            cases: 2,11,21,38,40
          - bash: "4.2"
            tmux: "2.6"
            cases: 3,11,13,20,21,30,51,54,57,62,72,83,84
          - bash: "4.2"
            tmux: "2.7"
            cases: 9,41,47,53,57,71,72,75,81
          - bash: "4.2"
            tmux: "2.8"
            cases: 25,26,30,43,58,59,66,67
          - bash: "4.2"
            tmux: "2.9"
            cases: 32,55
          - bash: "4.2"
            tmux: "2.9a"
            cases: 4,50,52,63,82
          - bash: "4.2"
            tmux: "3.0a"
            cases: 11,28,31,35,40,49,55,74
          - bash: "4.2"
            tmux: "3.1"
            cases: 22,33,37,40,46,53,65,81
          - bash: "4.2"
            tmux: "3.1b"
            cases: 7,9,19,28,29,36,45,51,54,56,72,81
          - bash: "4.2"
            tmux: "3.1c"
            cases: 46,54,58,73,78
          - bash: "4.2"
            tmux: "3.2"
            cases: 3,42,46,47,53,60,64,69,76,77
          - bash: "4.2"
            tmux: "3.3a"
            cases: 17,29,34,61,65,84
          - bash: "4.3"
            tmux: "1.8"
            cases: 8,11,20,24,38,47,65
          - bash: "4.3"
            tmux: "1.9"
            cases: 2,3,10,11,13,18,36,40,42,46,78,80
          - bash: "4.3"
            tmux: "1.9a"
            cases: 20,37,40,61,65,71
          - bash: "4.3"
            tmux: "2.0"
            cases: 1,2,14,16,25,26,32,37,41,47,49
          - bash: "4.3"
            tmux: "2.1"
            cases: 29,34,35,46,50,55,56,82
          - bash: "4.3"
            tmux: "2.2"
            cases: 1,7,16,18,29,42,45,46,48,76,78
          - bash: "4.3"
            tmux: "2.3"
            cases: 9,15,19,24,27,30,32,60,66,69
          - bash: "4.3"
            tmux: "2.4"
            cases: 14,18,45,60,80
          - bash: "4.3"
            tmux: "2.5"
            cases: 14,17,26,27,39,53,84
          - bash: "4.3"
            tmux: "2.6"
            cases: 24,25,38,49,56
          - bash: "4.3"
            tmux: "2.7"
            cases: 4,6,20,27,28,30,44,52,54,66,70,73,74,82
          - bash: "4.3"
            tmux: "2.8"
            cases: 21,39,64,78,81
          - bash: "4.3"
            tmux: "2.9"
            cases: 15,27,38,51,58,59
          - bash: "4.3"
            tmux: "2.9a"
            cases: 3,10,20,22,39,44,48,62,76,78,80
          - bash: "4.3"
            tmux: "3.0a"
            cases: 1,5,12,13,21,36,43,51,82
          - bash: "4.3"
            tmux: "3.1"
            cases: 2,17,19,28,29,32,57,58,60,72,77,83
          - bash: "4.3"
            tmux: "3.1b"
            cases: 4,5,11,33,42,47,64,70,84
          - bash: "4.3"
            tmux: "3.1c"
            cases: 18,29,31,36,68,75,76,77,79
          - bash: "4.3"
            tmux: "3.2"
            cases: 10,14,23,33,40,54,55,57,63
          - bash: "4.3"
            tmux: "3.3a"
            cases: 1,4,7,8,12,19,22,23,55,62,67,72
          - bash: "4.4"
            tmux: "1.8"
            cases: 15,22,27,42,43,44,58,62,68,81
          - bash: "4.4"
            tmux: "1.9"
            cases: 5,7,15,41,61,69,70,72,81,84
          - bash: "4.4"
            tmux: "1.9a"
            cases: 1,12,15,19,28,50,51,69,76,79,82
          - bash: "4.4"
            tmux: "2.0"
            cases: 12,18,30,61
          - bash: "4.4"
            tmux: "2.1"
            cases: 11,13,57,61
          - bash: "4.4"
            tmux: "2.2"
            cases: 9,21,25,27,28,40,64,81,84
          - bash: "4.4"
            tmux: "2.3"
            cases: 13,16,22,46,48,78
          - bash: "4.4"
            tmux: "2.4"
            cases: 4,17,28,35,44,50,59,64,69,72,77
          - bash: "4.4"
            tmux: "2.5"
            cases: 3,23,29,50,68,78,81
          - bash: "4.4"
            tmux: "2.6"
            cases: 7,32,34,37,42,44,47,71,74,77,81,82
          - bash: "4.4"
            tmux: "2.7"
            cases: 1,2,3,12,33,38,43,55,80
          - bash: "4.4"
            tmux: "2.8"
            cases: 6,7,14,19,31,44,62,71,79
          - bash: "4.4"
            tmux: "2.9"
            cases: 9,18,21,34,39,48,49,52,57,63,65,67,73,77,82
          - bash: "4.4"
            tmux: "2.9a"
            cases: 2,11,13,29,45,53,57,70
          - bash: "4.4"
            tmux: "3.0a"
            cases: 34,41,60,73,75
          - bash: "4.4"
            tmux: "3.1"
            cases: 5,10,14,26,31,36,39
          - bash: "4.4"
            tmux: "3.1b"
            cases: 3,6,13,14,22,39,40,52,53,57,83
          - bash: "4.4"
            tmux: "3.1c"
            cases: 15,26,35,39,49,64,67,70
          - bash: "4.4"
            tmux: "3.2"
            cases: 8,18,20,25,28,30,34,38,45,49,51,66,83
          - bash: "4.4"
            tmux: "3.3a"
            cases: 18,24,33,36,44,54,56,64,71,78,81
          - bash: "5.0"
            tmux: "1.8"
            cases: 4,25,26,37,55,57,77
          - bash: "5.0"
            tmux: "1.9"
            cases: 9,17,19,20,32,33,38,54,58,76,77,82,83
          - bash: "5.0"
            tmux: "1.9a"
            cases: 8,29,33,36,39,41,52,53,54,68,70,72,84
          - bash: "5.0"
            tmux: "2.0"
            cases: 10,43,46,69
          - bash: "5.0"
            tmux: "2.1"
            cases: 14,24,28,31,40,69,79
          - bash: "5.0"
            tmux: "2.2"
            cases: 6,11,13,35,39,56,61,62,79,82,83
          - bash: "5.0"
            tmux: "2.3"
            cases: 28,36,38,41,65
          - bash: "5.0"
            tmux: "2.4"
            cases: 7,27,29,32,67
          - bash: "5.0"
            tmux: "2.5"
            cases: 16,41,45,49,51,56,76
          - bash: "5.0"
            tmux: "2.6"
            cases: 5,15,17,18,22,58,70,79
          - bash: "5.0"
            tmux: "2.7"
            cases: 18,26,36,42,56,64,68,77
          - bash: "5.0"
            tmux: "2.8"
            cases: 18,23,33,34,52,60,68,69,76,77
          - bash: "5.0"
            tmux: "2.9"
            cases: 3,10,12,16,37,40,43,61,62,66,68,75,80
          - bash: "5.0"
            tmux: "2.9a"
            cases: 1,30,40,42
          - bash: "5.0"
            tmux: "3.0a"
            cases: 2,19,22,33,37,63,65,66
          - bash: "5.0"
            tmux: "3.1"
            cases: 7,11,12,25,44,55,71,78
          - bash: "5.0"
            tmux: "3.1b"
            cases: 35,49,50,59,67,69,78
          - bash: "5.0"
            tmux: "3.1c"
            cases: 2,3,5,17,21,22,27,34,38,50,53,55,56,65,74,81,82
          - bash: "5.0"
            tmux: "3.2"
            cases: 1,12,39,44,52,68,73
          - bash: "5.0"
            tmux: "3.3a"
            cases: 6,10,11,13,15,28,30,31,32,35,43,46,47,48,51,59,75,82
          - bash: "5.1"
            tmux: "1.8"
            cases: 10,13,19,35,40,45,46,76
          - bash: "5.1"
            tmux: "1.9"
            cases: 4,25,47,51
          - bash: "5.1"
            tmux: "1.9a"
            cases: 4,11,24,26,48,62,64,81
          - bash: "5.1"
            tmux: "2.0"
            cases: 15,19,22,33,40,44,51,53,56,72
          - bash: "5.1"
            tmux: "2.1"
            cases: 1,3,21,22,25,38,53,70,76,81
          - bash: "5.1"
            tmux: "2.2"
            cases: 23,24,31,49,50,58,68,80
          - bash: "5.1"
            tmux: "2.3"
            cases: 2,8,23,31,37,42,43,76,77,83
          - bash: "5.1"
            tmux: "2.4"
            cases: 5,6,8,10,19,24,30,46,55
          - bash: "5.1"
            tmux: "2.5"
            cases: 1,18,24,32,33,35,57,64,65,66,83
          - bash: "5.1"
            tmux: "2.6"
            cases: 12,29,40,41,46,55,63,68
          - bash: "5.1"
            tmux: "2.7"
            cases: 15,21,45,59,79
          - bash: "5.1"
            tmux: "2.8"
            cases: 5,17,20,28,42,57,61,70,75,82,84
          - bash: "5.1"
            tmux: "2.9"
            cases: 19,30,41,47,60,74,78,84
          - bash: "5.1"
            tmux: "2.9a"
            cases: 14,18,36,58,68,69,71
          - bash: "5.1"
            tmux: "3.0a"
            cases: 14,27,48,52,54,58,69,71,78,80
          - bash: "5.1"
            tmux: "3.1"
            cases: 1,8,30,34,68,74,79
          - bash: "5.1"
            tmux: "3.1b"
            cases: 8,16,17,43,48,62,65,73
          - bash: "5.1"
            tmux: "3.1c"
            cases: 7,9,10,16,44,48,71,83
          - bash: "5.1"
            tmux: "3.2"
            cases: 13,16,29,31,32,50,62,67,72,81
          - bash: "5.1"
            tmux: "3.3a"
            cases: 39,45,52,66,68,79
          - bash: "5.2"
            tmux: "1.8"
            cases: 2,6,7,17,18,28,33,36,61,69
          - bash: "5.2"
            tmux: "1.9"
            cases: 12,28,30,34,39,43,44,45,50,71
          - bash: "5.2"
            tmux: "1.9a"
            cases: 2,6,16,25,30,42,49
          - bash: "5.2"
            tmux: "2.0"
            cases: 3,5,8,21,24,29,58,64,70,77,80,81,84
          - bash: "5.2"
            tmux: "2.1"
            cases: 9,10,15,19,42,43,51,52,54,62,65,68,77,80
          - bash: "5.2"
            tmux: "2.2"
            cases: 8,32,37,38,53,55,69
          - bash: "5.2"
            tmux: "2.3"
            cases: 14,33,34,45,70,79,80
          - bash: "5.2"
            tmux: "2.4"
            cases: 13,20,21,26,31,47,53,65,66,78
          - bash: "5.2"
            tmux: "2.5"
            cases: 6,12,13,22,37,43,58,70
          - bash: "5.2"
            tmux: "2.6"
            cases: 14,26,43,53,64,66,67,69,73
          - bash: "5.2"
            tmux: "2.7"
            cases: 5,7,13,24,25,29,35,76,83
          - bash: "5.2"
            tmux: "2.8"
            cases: 2,4,8,11,12,15,16,22,41,48,55
          - bash: "5.2"
            tmux: "2.9"
            cases: 4,17,26,29,36,42,46,53,56,81
          - bash: "5.2"
            tmux: "2.9a"
            cases: 9,15,24,25,27,28,31,33,34,37,43,49,51,77,79
          - bash: "5.2"
            tmux: "3.0a"
            cases: 6,8,17,18,29,56,57,61,77,83
          - bash: "5.2"
            tmux: "3.1"
            cases: 38,41,47,48,59,63,70,82
          - bash: "5.2"
            tmux: "3.1b"
            cases: 10,20,24,34,38,44,46,61,68,71,77,82
          - bash: "5.2"
            tmux: "3.1c"
            cases: 1,4,12,20,23,25,30,51,60,72,80,84
          - bash: "5.2"
            tmux: "3.2"
            cases: 9,21,24,26,35,48,58,59,65,71,74,75
          - bash: "5.2"
            tmux: "3.3a"
            cases: 9,40,50,57,70
###END_INSERT###

    steps:
    - uses: actions/checkout@v2
    - name: Install dependency
      run: |
        apk add make curl gcc musl-dev libevent-dev ncurses-dev perl git util-linux bsd-compat-headers
        git clone -b v2.1.8 https://github.com/kward/shunit2.git test/shunit2

    - name: Install tmux
      run: |
        curl -L "https://github.com/tmux/tmux/releases/download/${{matrix.tmux}}/tmux-${{matrix.tmux}}.tar.gz" | tar zxv
        cd tmux-${{matrix.tmux}}
        ./configure
        make
        make install
        printf "set-window-option -g automatic-rename off\nset-option -g allow-rename off\n" >> "$HOME/.tmux.conf"

    - name: Unit test
      run: |
        script -e -c /bin/bash -c 'TERM=xterm bash ./test/unit.sh'

    - name: Scenario test
      run: |
        bash ./test/test_generator.sh ${{matrix.cases}} > ./test/cases_pairwise.sh
        script -e -c /bin/bash -c 'stty rows 40 cols 80;TERM=xterm bash ./test/cases_pairwise.sh'
